import { CreateMLCEngine, prebuiltAppConfig } from 'https://cdn.jsdelivr.net/npm/@mlc-ai/web-llm@0.2.84/+esm';

const MARKER='LOCAL_AGENT_V9';
const $=id=>document.getElementById(id);
const passthrough=window.fetch.bind(window);
const appConfig={...prebuiltAppConfig,cacheBackend:'indexeddb'};
let engine=null,model='',busy=false,quality='deep';

const prefs=[
  [/Qwen3.*8B.*Instruct.*q4f16/i,'Qwen3 8B · máxima qualidade'],
  [/Llama-3\.1-8B-Instruct-q4f16/i,'Llama 3.1 8B · máxima qualidade'],
  [/Qwen3.*4B.*Instruct.*q4f16/i,'Qwen3 4B · recomendado'],
  [/Phi-3\.5-mini-instruct-q4f16/i,'Phi 3.5 Mini · equilibrado'],
  [/Llama-3\.2-3B-Instruct-q4f16/i,'Llama 3.2 3B · equilibrado'],
  [/Qwen2\.5-1\.5B-Instruct-q4f16/i,'Qwen2.5 1.5B · leve']
];
const records=prebuiltAppConfig.model_list||[];
const models=[];
for(const [re,label] of prefs){const r=records.find(x=>re.test(x.model_id));if(r&&!models.some(x=>x.id===r.model_id))models.push({id:r.model_id,label,vram:Number(r.estimated_vram_bytes||0)});}
if(!models.length){const r=records.find(x=>/Instruct.*q4f16/i.test(x.model_id));if(r)models.push({id:r.model_id,label:r.model_id,vram:Number(r.estimated_vram_bytes||0)});}

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=s=>String(s??'').replace(/<think>[\s\S]*?<\/think>/gi,'').replace(/```(?:json)?/gi,'').replace(/```/g,'').replace(/^\s{0,3}#{1,6}\s*/gm,'').replace(/\*\*(.*?)\*\*/g,'$1').trim();
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json'}});
const headers=h=>{const o={};if(h instanceof Headers)h.forEach((v,k)=>o[k.toLowerCase()]=v);else Object.entries(h||{}).forEach(([k,v])=>o[String(k).toLowerCase()]=v);return o;};

function status(text,state='idle'){
  if($('localAiStatus')){$('localAiStatus').textContent=text;$('localAiStatus').dataset.state=state;}
  if($('aiTopStatus'))$('aiTopStatus').textContent=state==='ready'?'IA local agêntica':state==='loading'?'IA analisando':'Motor local';
  $('aiDot')?.classList.toggle('on',state==='ready'||state==='loading');
}
function progress(r){if($('localAiProgressBar'))$('localAiProgressBar').style.width=`${Math.max(0,Math.min(100,Number(r?.progress||0)*100))}%`;status(r?.text||'Preparando modelo…','loading');}
function promptParts(body){return{system:(body?.systemInstruction?.parts||[]).map(p=>p.text||'').join('\n'),user:(body?.contents||[]).flatMap(c=>c.parts||[]).map(p=>p.text||'').join('\n\n')};}
function marked(text,key,next=[]){const s=clean(text),i=s.search(new RegExp(`${key}\\s*:`,`i`));if(i<0)return'';const tail=s.slice(i).replace(new RegExp(`^${key}\\s*:\\s*`,`i`),'');let end=tail.length;for(const n of next){const p=tail.search(new RegExp(`\\n\\s*${n}\\s*:`,`i`));if(p>=0)end=Math.min(end,p);}return tail.slice(0,end).trim();}
function source(user){
  const question=(user.match(/Pergunta principal:\s*([^\n]+)/i)?.[1]||'O que esta experiência ajuda o casal a compreender?').trim();
  const participants=(user.match(/Participantes:\s*([^\.\n]+)/i)?.[1]||'o casal').trim();
  const cards=[],re=/(Clima atual|Ponte de conexão|Próximo passo)\s+—\s+([^:|]+):\s*núcleo=([^;|]+);\s*potência=([^;|]+);\s*sombra=([^;|]+);\s*convite=([^|\n]+)/gi;let m;
  while((m=re.exec(user)))cards.push({posicao:m[1].trim(),carta:m[2].trim(),core:m[3].trim(),light:m[4].trim(),shadow:m[5].trim(),invitation:m[6].trim()});
  return{question,participants,cards,raw:user};
}
function agentPanel(){
  $('reading')?.classList.remove('hidden');$('readingLoading')?.classList.remove('hidden');
  let p=$('localAgentPanel');if(!p&&$('reading')){p=document.createElement('section');p.id='localAgentPanel';p.className='local-agent-panel';p.innerHTML='<div class="agent-head"><span class="agent-orb"></span><div><b>Leitura local agêntica</b><small id="agentStage">Preparando</small></div><span id="agentProgress">0%</span></div><div class="agent-track"><i id="agentTrackBar"></i></div><div id="agentLiveText" class="agent-live-text" aria-live="polite"></div><div id="agentSteps" class="agent-steps"></div>';$('reading').insertBefore(p,$('readingSections')||null);}p?.classList.remove('hidden');return p;
}
function stage(i,total,title,text=''){
  agentPanel();const pc=Math.round(i/total*100);if($('agentStage'))$('agentStage').textContent=title;if($('agentProgress'))$('agentProgress').textContent=`${pc}%`;if($('agentTrackBar'))$('agentTrackBar').style.width=`${pc}%`;if(text&&$('agentLiveText'))$('agentLiveText').textContent=text.slice(-6000);
  const labels=['Cartas','Conexões','Dimensões','Plano','Revisão'];if($('agentSteps'))$('agentSteps').innerHTML=labels.map((x,n)=>`<span class="${n<i?'done':n===i?'active':''}">${n<i?'✓':n+1} ${x}</span>`).join('');
}
async function ask(messages,{tokens=800,temp=.52,i=1,total=6,title='Analisando'}={}){
  const chunks=await engine.chat.completions.create({messages,temperature:temp,top_p:.9,repetition_penalty:1.08,presence_penalty:.15,max_tokens:tokens,stream:true,stream_options:{include_usage:true}});let out='';
  for await(const chunk of chunks){out+=chunk?.choices?.[0]?.delta?.content||'';stage(i,total,title,clean(out));}
  if(!out.trim()&&engine.getMessage)out=String(await engine.getMessage()||'');return clean(out);
}
const fallback=c=>({posicao:c.posicao,carta:c.carta,interpretacao:`${c.carta} coloca ${c.core} no centro desta posição e pede observação concreta.`,potencial:c.light||`O potencial está em ${c.core}.`,sombra:c.shadow||'Evitem transformar símbolo em certeza.',convite:c.invitation||'Que atitude concreta esclarece esta posição?'});
async function card(c,ctx,i,total){
  const text=await ask([{role:'system',content:'Você interpreta Lenormand com profundidade, sem prever fatos nem afirmar sentimentos ocultos. Escreva em português do Brasil.'},{role:'user',content:`Participantes: ${ctx.participants}. Pergunta: ${ctx.question}. Posição: ${c.posicao}. Carta: ${c.carta}. Núcleo: ${c.core}. Potência: ${c.light}. Sombra: ${c.shadow}. Convite: ${c.invitation}.\nResponda sem Markdown:\nINTERPRETACAO: 90 a 150 palavras específicas.\nPOTENCIAL: 35 a 70 palavras.\nSOMBRA: 35 a 70 palavras.\nCONVITE: uma pergunta concreta.`}],{tokens:650,temp:.58,i,total,title:`Interpretando ${c.carta}`});
  const r=fallback(c);r.interpretacao=marked(text,'INTERPRETACAO',['POTENCIAL','SOMBRA','CONVITE'])||r.interpretacao;r.potencial=marked(text,'POTENCIAL',['SOMBRA','CONVITE'])||r.potencial;r.sombra=marked(text,'SOMBRA',['CONVITE'])||r.sombra;r.convite=marked(text,'CONVITE')||r.convite;return r;
}
async function synth(ctx,pos,i,total){
  const text=await ask([{role:'system',content:'Você é diretora de síntese. Cruze cartas sem repetir definições e sem tratar símbolos como fatos.'},{role:'user',content:`Participantes: ${ctx.participants}. Pergunta: ${ctx.question}. Posições: ${JSON.stringify(pos)}. Contexto da sessão: ${ctx.raw.slice(0,4500)}.\nResponda sem Markdown:\nVISAO_GERAL: 180 a 280 palavras.\nRESPOSTA: 140 a 220 palavras respondendo diretamente.\nCOMBINACAO: 140 a 220 palavras sobre como as cartas alteram o sentido umas das outras.`}],{tokens:1100,temp:.5,i,total,title:'Cruzando as três cartas'});
  return{visaoGeral:marked(text,'VISAO_GERAL',['RESPOSTA','COMBINACAO'])||'A sequência precisa ser verificada na conversa entre vocês.',respostaPergunta:marked(text,'RESPOSTA',['COMBINACAO'])||`Sobre “${ctx.question}”, transformem símbolos em observações e acordos.`,combinacao:marked(text,'COMBINACAO')||`${pos.map(x=>x.carta).join(', ')} conectam clima, ponte e próximo passo.`};
}
async function dims(ctx,pos,syn,i,total){
  const text=await ask([{role:'system',content:'Você diferencia atração, carinho, confiança, comunicação, expectativas e intenção sem diagnosticar pessoas.'},{role:'user',content:`Pergunta: ${ctx.question}. Posições: ${JSON.stringify(pos)}. Síntese: ${JSON.stringify(syn)}.\nResponda sem Markdown, 45 a 85 palavras por dimensão:\nATRACAO:\nCARINHO:\nCONFIANCA:\nCOMUNICACAO:\nEXPECTATIVAS:\nINTENCAO:\nATENCAO:`}],{tokens:1000,temp:.46,i,total,title:'Separando dimensões da relação'});
  const n=['CARINHO','CONFIANCA','COMUNICACAO','EXPECTATIVAS','INTENCAO','ATENCAO'];return{dimensoes:{atracao:marked(text,'ATRACAO',n)||'A atração deve ser confirmada por sinais observáveis.',carinho:marked(text,'CARINHO',n.slice(1))||'O carinho aparece em cuidado e presença.',confianca:marked(text,'CONFIANCA',n.slice(2))||'A confiança cresce por constância.',comunicacao:marked(text,'COMUNICACAO',n.slice(3))||'A comunicação reduz suposições.',expectativas:marked(text,'EXPECTATIVAS',n.slice(4))||'Expectativas precisam ser nomeadas.',intencao:marked(text,'INTENCAO',['ATENCAO'])||'Intenção só se confirma por escolhas.'},pontoAtencao:marked(text,'ATENCAO')||'Não usem as cartas como prova sobre pensamentos ou futuro.'};
}
async function plan(ctx,pos,syn,dim,i,total){
  const text=await ask([{role:'system',content:'Você transforma reflexão em ações pequenas, realistas e consentidas.'},{role:'user',content:`Participantes: ${ctx.participants}. Pergunta: ${ctx.question}. Cartas: ${pos.map(x=>x.carta).join(', ')}. Síntese: ${syn.respostaPergunta}. Atenção: ${dim.pontoAtencao}.\nResponda sem Markdown:\nACAO_1: para hoje.\nACAO_2: conversa em até sete dias.\nACAO_3: ritual de continuidade.\nACAO_4: opcional.\nPERGUNTA_FINAL: específica e memorável.`}],{tokens:650,temp:.54,i,total,title:'Criando um plano específico'});
  const actions=[1,2,3,4].map(n=>marked(text,`ACAO_${n}`,n<4?[`ACAO_${n+1}`,'PERGUNTA_FINAL']:['PERGUNTA_FINAL'])).filter(Boolean);while(actions.length<3)actions.push(pos[actions.length]?.convite||'Escolham uma ação pequena e definam quando realizá-la.');return{planoPratico:actions.slice(0,4),perguntaFinal:marked(text,'PERGUNTA_FINAL')||'Qual atitude mostrará que esta conversa produziu proximidade real?'};
}
async function agentic(body){
  const {user}=promptParts(body),ctx=source(user);if(ctx.cards.length!==3)throw new Error('Não identifiquei as três cartas da tiragem.');const total=quality==='studio'?7:6;stage(0,total,'Organizando pergunta',`Pergunta: ${ctx.question}\nCartas: ${ctx.cards.map(x=>x.carta).join(' · ')}`);
  const pos=[];for(let i=0;i<3;i++)pos.push(await card(ctx.cards[i],ctx,i+1,total));const syn=await synth(ctx,pos,4,total),dim=await dims(ctx,pos,syn,5,total),pl=await plan(ctx,pos,syn,dim,6,total);
  const result={visaoGeral:syn.visaoGeral,respostaPergunta:syn.respostaPergunta,posicoes:pos,combinacao:syn.combinacao,dimensoes:dim.dimensoes,pontoAtencao:dim.pontoAtencao,planoPratico:pl.planoPratico,perguntaFinal:pl.perguntaFinal};stage(total,total,'Leitura concluída','A versão final está sendo organizada no layout.');setTimeout(()=>$('localAgentPanel')?.classList.add('hidden'),1000);return JSON.stringify(result);
}
async function normal(body){const {system,user}=promptParts(body),schema=body?.generationConfig?.responseJsonSchema;const chunks=await engine.chat.completions.create({messages:[{role:'system',content:`${system}\nResponda em português do Brasil, com especificidade e sem Markdown desnecessário. ${schema?'Retorne somente JSON válido.':''}`},{role:'user',content:user}],temperature:.5,top_p:.9,repetition_penalty:1.06,max_tokens:Math.min(Number(body?.generationConfig?.maxOutputTokens)||2200,4096),stream:true});let out='';for await(const c of chunks)out+=c?.choices?.[0]?.delta?.content||'';return clean(out);}
async function complete(body){if(!engine||!model)throw new Error('A IA local ainda não foi ativada.');if(busy)throw new Error('A IA local já está trabalhando.');busy=true;const {system,user}=promptParts(body),tarot=/baralho cigano|lenormand|tar[oô]/i.test(`${system}\n${user}`);status(tarot?'Agente local interpretando o Tarô…':'IA local elaborando resposta…','loading');try{const text=tarot?await agentic(body):await normal(body);status(`IA local agêntica · ${model}`,'ready');return json({candidates:[{content:{parts:[{text}]},finishReason:'STOP'}]});}finally{busy=false;}}
window.fetch=async(input,init={})=>{const url=typeof input==='string'?input:input?.url||'',h=headers(init.headers||input?.headers),key=h['x-goog-api-key']||'';if(url.includes('generativelanguage.googleapis.com/v1beta/models')&&key===MARKER)return json({models:[{name:'models/local-webllm',displayName:`IA local agêntica · ${model||'WebLLM'}`,supportedGenerationMethods:['generateContent']}]});if(url.includes('generativelanguage.googleapis.com')&&url.includes(':generateContent')&&(key===MARKER||url.includes('/local-webllm:generateContent'))){try{return await complete(JSON.parse(init.body||'{}'));}catch(e){return json({error:{message:e?.message||'Falha na IA local.'}},503);}}return passthrough(input,init);};
async function activate(){if(!('gpu'in navigator)){status('Este navegador não oferece WebGPU. Use Chrome ou Edge atualizados.','error');return;}const selected=$('localModel')?.value||models[0]?.id;if(!selected)return;const b=$('activateLocalAi');if(b){b.disabled=true;b.textContent='Preparando modelo…';}try{if(!engine||model!==selected){if(engine?.unload)await engine.unload().catch(()=>{});engine=await CreateMLCEngine(selected,{appConfig,initProgressCallback:progress},{context_window_size:4096,repetition_penalty:1.06});model=selected;}if($('geminiKey'))$('geminiKey').value=MARKER;document.querySelector('[data-action="connect-ai"]')?.click();setTimeout(()=>{if($('geminiModel'))$('geminiModel').value='local-webllm';if($('aiState'))$('aiState').textContent=`IA local agêntica · ${model}`;status(`IA local agêntica · ${model}`,'ready');if($('hostRole'))$('hostRole').textContent='Diretora local';if($('hostMessage'))$('hostMessage').textContent='A leitura será construída em etapas: cartas, conexões, dimensões e plano.';if($('hostMode'))$('hostMode').textContent='agente local multi-etapas';},300);}catch(e){status(`Não foi possível carregar o modelo: ${e?.message||e}`,'error');}finally{if(b){b.disabled=false;b.textContent=engine?'IA local ativada':'Baixar e ativar IA local';}}}
function deactivate(){if($('geminiKey')?.value===MARKER)$('geminiKey').value='';document.querySelector('[data-action="disconnect-ai"]')?.click();status('IA local desativada. O motor básico continua funcionando.','idle');}
function inject(){
  if(!document.querySelector('link[href*="visual-v9.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='visual-v9.css?v=9.0';document.head.appendChild(l);}document.body.dataset.edition='v9';
  const hero=document.querySelector('.hero');if(hero&&!hero.querySelector('.hero-orbit')){const v=document.createElement('div');v.className='hero-orbit';v.setAttribute('aria-hidden','true');v.innerHTML='<img src="assets/spark-orbit.svg?v=9.0" alt=""><span class="orbit-core">♥</span><i class="orbit-spark spark-a">✦</i><i class="orbit-spark spark-b">✦</i>';hero.appendChild(v);}document.querySelectorAll('.hero .eyebrow').forEach(e=>e.textContent='Couple Experience · v9.0 Agentic Local AI');const hp=document.querySelector('.hero>p');if(hp)hp.textContent='Uma experiência com 96 cartas e IA local que interpreta cada símbolo antes de construir o sentido completo.';
  const panel=$('aiPanel');if(panel){panel.innerHTML=`<div class="ai-head"><div><span class="eyebrow">Inteligência privada</span><h3>IA local agêntica em múltiplas etapas</h3><p>O agente interpreta cada carta, cruza a sequência, separa dimensões e cria um plano específico para a pergunta.</p></div><span class="connection" id="aiState">Motor local básico</span></div><section id="localAiControls" class="local-ai-card"><div class="ai-control-grid"><label>Modelo local<select id="localModel">${models.map(x=>`<option value="${esc(x.id)}">${esc(x.label)}${x.vram?` · ~${(x.vram/1073741824).toFixed(1)} GB VRAM`:''}</option>`).join('')}</select></label><label>Profundidade<select id="localQuality"><option value="deep">Profunda · múltiplas etapas</option><option value="studio">Studio · revisão editorial</option></select></label></div><div class="local-ai-progress"><i id="localAiProgressBar"></i></div><p id="localAiStatus" data-state="idle">Modelos maiores entregam melhor interpretação, mas exigem mais memória.</p><div class="button-row"><button class="btn secondary" id="activateLocalAi" type="button">Baixar e ativar IA local</button><button class="btn text" id="deactivateLocalAi" type="button">Desativar IA local</button></div></section><details class="external-ai-details"><summary>Gemini opcional</summary><div class="ai-fields"><label>Chave Gemini<input id="geminiKey" type="password" autocomplete="off" placeholder="Opcional"></label><label>Modelo<select id="geminiModel"><option value="">Conecte para listar modelos</option></select></label></div><div class="button-row"><button class="btn ghost" data-action="connect-ai">Conectar Gemini</button><button class="btn text" data-action="disconnect-ai">Desconectar</button></div></details><small id="aiHelp">A IA local não usa créditos. A qualidade depende do modelo, GPU e memória.</small>`;$('activateLocalAi')?.addEventListener('click',activate);$('deactivateLocalAi')?.addEventListener('click',deactivate);$('localQuality')?.addEventListener('change',e=>quality=e.target.value);}
  const cr=document.querySelector('#view-credits .credits p');if(cr)cr.textContent='Conceito, direção criativa e autoria de Primeira Faísca. Edição v9.0 com 96 cartas, IA local agêntica e direção visual premium.';
}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if((a==='draw-tarot'||a==='retry-tarot')&&engine&&model)setTimeout(()=>{if($('readingSections'))$('readingSections').innerHTML='<div class="agent-placeholder"><span class="agent-orb"></span><div><b>A interpretação agêntica foi iniciada.</b><p>A leitura será construída carta por carta e reunida em uma síntese única.</p></div></div>';if($('readingEngine'))$('readingEngine').textContent='IA local agêntica';agentPanel();},0);},true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject,{once:true});else inject();
