const $=id=>document.getElementById(id);
const views=['home','setup','game','result','dice','tarot','kit','credits'];
const phases=[
  {id:'abertura',icon:'○',title:'Abertura',description:'Reduzir tensão, criar presença e começar por temas fáceis.',cats:['conversa']},
  {id:'descoberta',icon:'◎',title:'Descoberta',description:'Entender hábitos, preferências e compatibilidade prática.',cats:['afinidade']},
  {id:'conexao',icon:'◇',title:'Conexão',description:'Aprofundar confiança, apoio, limites e segurança emocional.',cats:['vinculo']},
  {id:'romance',icon:'♥',title:'Romance',description:'Nomear afeto, interesse e formas confortáveis de proximidade.',cats:['romance','faisca']},
  {id:'experiencia',icon:'↗',title:'Experiência',description:'Transformar conversa em uma atividade compartilhada e consentida.',cats:['desafio']}
];
let state={p1:'',p2:'',level:2,total:18,deck:[],index:0,answered:0,skipped:0,favorites:0,spark:0,fav:false,categories:{},phaseStats:{},insights:[],favoriteCards:[],lastDice:'',currentPhase:'abertura'};
let deferredPrompt=null,geminiKey='',spotifyController=null,musicPlaying=false,userInteracted=false,lastTarotRequest=null;

function show(view){views.forEach(v=>$(v).classList.toggle('hidden',v!==view));document.querySelectorAll('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));window.scrollTo({top:0,behavior:'smooth'});if(view==='tarot')renderAutoContext();}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2600);}
function title(s){return s?String(s).charAt(0).toUpperCase()+String(s).slice(1):'';}
function escapeHtml(value=''){return String(value).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
function setAIState(text,kind=''){$('aiState').textContent=text;$('aiState').className=`aiState ${kind}`.trim();}
function setMusicStatus(text,kind=''){$('musicStatus').textContent=text;$('musicStatus').className=`musicStatus ${kind}`.trim();}

function allocateCounts(total){if(total===12)return[3,2,3,2,2];if(total===24)return[5,5,5,5,4];return[4,4,4,4,2];}
function eligibleForPhase(phase){let pool=cards.filter(c=>phase.cats.includes(c.c)&&c.l<=state.level);if(!pool.length&&phase.id==='romance'&&state.level===1)pool=cards.filter(c=>c.c==='romance'&&c.l===2);return pool;}
function buildJourney(){const counts=allocateCounts(state.total);const used=new Set();const deck=[];phases.forEach((phase,i)=>{let pool=shuffle(eligibleForPhase(phase));let selected=[];for(const card of pool){const key=card.q;if(!used.has(key)){selected.push({...card,phaseId:phase.id});used.add(key);}if(selected.length===counts[i])break;}if(selected.length<counts[i]){const fallback=shuffle(cards.filter(c=>c.l<=state.level&&!used.has(c.q)));for(const card of fallback){selected.push({...card,phaseId:phase.id});used.add(card.q);if(selected.length===counts[i])break;}}deck.push(...selected);});return deck.slice(0,state.total);}
function startGame(){const p1=$('p1').value.trim(),p2=$('p2').value.trim();if(!p1||!p2){$('setupError').textContent='Preencha os dois nomes para iniciar.';return;}state={...state,p1,p2,total:Number($('duration').value),deck:[],index:0,answered:0,skipped:0,favorites:0,spark:0,fav:false,categories:{},phaseStats:{},insights:[],favoriteCards:[],lastDice:'',currentPhase:'abertura'};state.deck=buildJourney();phases.forEach(p=>state.phaseStats[p.id]={seen:0,answered:0,skipped:0});$('setupError').textContent='';renderPhaseRail();show('game');renderCard();}
function renderPhaseRail(){const current=state.deck[state.index]?.phaseId||'experiencia';const currentIndex=phases.findIndex(p=>p.id===current);$('phaseRail').innerHTML=phases.map((p,i)=>`<div class="phaseDot ${i<currentIndex?'done':i===currentIndex?'active':''}"><b>${p.icon}</b><span>${p.title}</span></div>`).join('');}
function renderCard(){if(state.index>=state.deck.length){finishGame();return;}const card=state.deck[state.index],phase=phases.find(p=>p.id===card.phaseId)||phases[0];if(state.currentPhase!==phase.id){state.currentPhase=phase.id;toast(`Nova etapa: ${phase.title}`);}state.fav=false;$('favorite').textContent='♡';$('favorite').classList.remove('on');$('categoryBadge').textContent=`${icons[card.c]||'◌'} ${title(card.c)}`;$('levelBadge').textContent=`Nível ${card.l}`;$('turn').textContent=`Vez de ${state.index%2===0?state.p1:state.p2}`;$('question').textContent=card.q;$('why').textContent=card.w;$('how').textContent=card.h;$('consentNote').textContent=card.d?'Desafio de proximidade: só acontece com concordância clara dos dois. Adaptar ou escolher outra opção também é válido.':'Respondam no nível de detalhe que seja confortável para ambos.';$('roundMeta').textContent=`${state.index+1} de ${state.deck.length}`;$('progressBar').style.width=`${(state.index/state.deck.length)*100}%`;$('phaseIcon').textContent=phase.icon;$('phaseTitle').textContent=phase.title;$('phaseDescription').textContent=phase.description;$('insightInput').value='';renderPhaseRail();}
function advance(kind){const card=state.deck[state.index];state.categories[card.c]=(state.categories[card.c]||0)+1;state.phaseStats[card.phaseId].seen++;if(kind==='answered'){state.answered++;state.spark+=card.d?2:1;state.phaseStats[card.phaseId].answered++;}else{state.skipped++;state.phaseStats[card.phaseId].skipped++;}if(state.fav){state.favorites++;state.favoriteCards.push(card.q);}state.index++;renderCard();}
function adaptCurrent(){const card=state.deck[state.index];$('question').textContent=`Versão adaptada: ${card.q.replace(/\?$/,'')} — responda somente a parte que fizer sentido agora.`;$('how').textContent='Reduzam o nível de detalhe, troquem o exemplo ou respondam de forma geral. A intenção da carta permanece a mesma.';toast('Pergunta adaptada sem perder o objetivo.');}
function saveInsight(){const value=$('insightInput').value.trim();if(!value){toast('Escreva um insight antes de guardar.');return;}if(state.insights.length>=10){toast('Limite de 10 insights alcançado.');return;}state.insights.push(value);$('insightInput').value='';toast('Insight guardado para a síntese.');}
function openSkip(){pickAlternative();$('skipModal').classList.remove('hidden');}
function pickAlternative(){$('alternative').textContent=alternatives[Math.floor(Math.random()*alternatives.length)];}
function finishGame(){$('progressBar').style.width='100%';$('answeredStat').textContent=state.answered;$('skippedStat').textContent=state.skipped;$('favStat').textContent=state.favorites;$('sparkStat').textContent=state.spark;$('resultText').textContent=`${state.p1} e ${state.p2} concluíram uma sequência de ${state.deck.length} cartas em cinco etapas. Os dados e o Tarô agora podem usar os sinais desta jornada.`;$('phaseSummary').innerHTML=phases.map(p=>{const x=state.phaseStats[p.id]||{};return `<div class="summaryRow"><b>${p.icon} ${p.title}</b><span>${x.answered||0} respondidas · ${x.skipped||0} alternativas</span></div>`}).join('');$('insightSummary').innerHTML=state.insights.length?state.insights.map(x=>`<div class="insightPill">${escapeHtml(x)}</div>`).join(''):'<p class="muted">Nenhum insight foi registrado. A leitura ainda usará as estatísticas e as cartas favoritas.</p>';show('result');}

const dice={action:['Dar as mãos','Abraço confortável','Contato visual','Dança curta','Carinho nas mãos','Gesto escolhido juntos'],time:['5 segundos','10 segundos','15 segundos','20 segundos','30 segundos','45 segundos'],mood:['divertido','carinhoso','calmo','romântico','criativo','surpresa conjunta']};
function rollDice(){['dieAction','dieTime','dieMood'].forEach(id=>{const el=$(id);el.classList.remove('rolling');void el.offsetWidth;el.classList.add('rolling');});const a=Math.floor(Math.random()*6),t=Math.floor(Math.random()*6),m=Math.floor(Math.random()*6);setTimeout(()=>{$('dieAction').querySelector('.dieNum').textContent=a+1;$('dieAction').querySelector('b').textContent=dice.action[a];$('dieTime').querySelector('.dieNum').textContent=t+1;$('dieTime').querySelector('b').textContent=dice.time[t];$('dieMood').querySelector('.dieNum').textContent=m+1;$('dieMood').querySelector('b').textContent=title(dice.mood[m]);$('diceCombo').textContent=`${dice.action[a]} por ${dice.time[t]}, de modo ${dice.mood[m]}.`;$('diceSaved').textContent='';},420);}
function saveDice(){state.lastDice=$('diceCombo').textContent.trim();$('diceSaved').textContent='✓ Resultado guardado e pronto para integrar a leitura.';toast('Resultado dos dados adicionado ao contexto do Tarô.');}

function renderAutoContext(){const topCat=Object.entries(state.categories).sort((a,b)=>b[1]-a[1])[0]?.[0];const parts=[];if(state.p1&&state.p2)parts.push(`${state.p1} + ${state.p2}`);if(state.answered||state.skipped)parts.push(`${state.answered} respondidas`,`${state.skipped} alternativas`);if(topCat)parts.push(`ênfase em ${topCat}`);if(state.insights.length)parts.push(`${state.insights.length} insights`);if(state.lastDice)parts.push('dados salvos');$('autoContext').textContent=parts.length?`Contexto automático: ${parts.join(' · ')}.`:'Ainda não existe uma jornada anterior. A leitura usará apenas a pergunta e as cartas.';}
function relationshipSystem(){return 'Você é um intérprete técnico, sensível e responsável do Baralho Cigano Lenormand dentro do jogo de casal Primeira Faísca. Trate cartas como símbolos de reflexão e diálogo. Nunca afirme que conhece pensamentos secretos, sentimentos ocultos ou acontecimentos futuros como fatos. Não use fatalismo, manipulação, diagnóstico ou linguagem ameaçadora. Diferencie com precisão atração, carinho, confiança, comunicação, expectativa, intenção e compatibilidade. Produza análises específicas, coerentes com as cartas e com o contexto fornecido. Não omita nenhuma seção solicitada.';}
function buildTarotContext(selected,q,extra){const roles=['Clima atual','Ponte de conexão','Próximo passo'];const topCat=Object.entries(state.categories).sort((a,b)=>b[1]-a[1])[0]?.[0]||'não identificada';const cardsText=selected.map((c,i)=>`${roles[i]} — ${c[1]}: núcleo=${c[3]}; potência=${c[4]}; sombra=${c[5]}; pergunta reflexiva=${c[6]}`).join('\n');return `Pergunta principal: ${q||'Leitura aberta sobre a conexão construída nesta experiência.'}\nParticipantes: ${state.p1&&state.p2?`${state.p1} e ${state.p2}`:'casal sem nomes informados'}.\nIntensidade escolhida: nível ${state.level}.\nParticipação: ${state.answered} respondidas, ${state.skipped} alternativas, ${state.favorites} favoritas e ${state.spark} pontos de faísca.\nCategoria predominante: ${topCat}.\nCartas favoritas: ${state.favoriteCards.length?state.favoriteCards.join(' | '):'nenhuma'}.\nInsights registrados: ${state.insights.length?state.insights.join(' | '):'nenhum'}.\nResultado dos dados: ${state.lastDice||'não utilizado'}.\nContexto adicional do casal: ${extra||'não informado'}.\n\nCartas sorteadas:\n${cardsText}\n\nConstrua uma leitura completa, profunda e clara. A resposta deve preencher integralmente todos os campos do esquema, sem frases genéricas e sem repetir a mesma ideia em seções diferentes.`;}
const readingSchema={type:'object',required:['visaoGeral','respostaPergunta','posicoes','combinacao','dimensoes','pontoAtencao','planoPratico','perguntaFinal'],properties:{visaoGeral:{type:'string',description:'Síntese profunda da tiragem e do contexto, com 2 a 4 parágrafos.'},respostaPergunta:{type:'string',description:'Resposta reflexiva e direta à pergunta principal, sem previsões factuais.'},posicoes:{type:'array',minItems:3,maxItems:3,items:{type:'object',required:['posicao','carta','interpretacao','potencial','sombra','convite'],properties:{posicao:{type:'string'},carta:{type:'string'},interpretacao:{type:'string'},potencial:{type:'string'},sombra:{type:'string'},convite:{type:'string'}}}},combinacao:{type:'string',description:'Análise da interação entre as três cartas como conjunto.'},dimensoes:{type:'object',required:['atracao','carinho','confianca','comunicacao','expectativas','intencao'],properties:{atracao:{type:'string'},carinho:{type:'string'},confianca:{type:'string'},comunicacao:{type:'string'},expectativas:{type:'string'},intencao:{type:'string'}}},pontoAtencao:{type:'string'},planoPratico:{type:'array',minItems:3,maxItems:5,items:{type:'string'}},perguntaFinal:{type:'string'}}};
async function listModels(key){const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models?pageSize=100',{headers:{'x-goog-api-key':key}});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||`Erro ${response.status}`);return (data.models||[]).filter(m=>{const methods=m.supportedGenerationMethods||m.supportedActions||[];return methods.includes('generateContent')&&/gemini/i.test(m.name||'');}).map(m=>(m.name||'').replace(/^models\//,''));}
function chooseModels(models){const preferred=['gemini-3.6-flash','gemini-3.5-flash','gemini-3.1-flash','gemini-3-flash'];const ordered=[...preferred.filter(x=>models.includes(x)),...models.filter(x=>/flash/i.test(x)&&!preferred.includes(x))];return [...new Set(ordered)].slice(0,12);}
async function connectAI(){const key=$('geminiKey').value.trim();if(key.length<20){setAIState('Chave inválida','error');toast('Cole uma chave válida.');return;}geminiKey=key;setAIState('Consultando modelos…');$('connectAI').disabled=true;try{const available=chooseModels(await listModels(key));if(!available.length)throw new Error('Nenhum modelo Gemini Flash compatível foi encontrado.');$('geminiModel').innerHTML=available.map((m,i)=>`<option value="${escapeHtml(m)}" ${i===0?'selected':''}>${escapeHtml(m)}</option>`).join('');await callGemini('Responda somente com a palavra CONECTADO.',available[0],{structured:false,maxOutputTokens:30,thinkingLevel:'minimal'});setAIState('IA conectada','connected');$('geminiKey').value='';toast(`Conectado a ${available[0]}.`);}catch(error){geminiKey='';setAIState('Falha na conexão','error');toast(error.message.slice(0,150));}finally{$('connectAI').disabled=false;}}
function disconnectAI(){geminiKey='';$('geminiKey').value='';setAIState('Não conectado');toast('Chave removida da memória.');}
async function callGemini(prompt,model,opts={}){const structured=opts.structured!==false;const generationConfig={maxOutputTokens:opts.maxOutputTokens||7000,thinkingConfig:{thinkingLevel:opts.thinkingLevel||'high'}};if(structured){generationConfig.responseMimeType='application/json';generationConfig.responseJsonSchema=readingSchema;}const body={system_instruction:{parts:[{text:relationshipSystem()}]},contents:[{role:'user',parts:[{text:prompt}]}],generationConfig};const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':geminiKey},body:JSON.stringify(body)});let data={};try{data=await response.json();}catch{}if(!response.ok)throw new Error(data?.error?.message||`Erro ${response.status}`);const candidate=data?.candidates?.[0];const text=candidate?.content?.parts?.map(p=>p.text||'').join('').trim();const finishReason=candidate?.finishReason||'DESCONHECIDO';if(!text)throw new Error(`A IA não retornou texto. Motivo: ${finishReason}.`);return{text,finishReason,usage:data.usageMetadata||{}};}
function parseStructured(text){let clean=text.trim().replace(/^```json\s*/i,'').replace(/```$/,'').trim();const data=JSON.parse(clean);const required=['visaoGeral','respostaPergunta','posicoes','combinacao','dimensoes','pontoAtencao','planoPratico','perguntaFinal'];const missing=required.filter(k=>data[k]==null||(typeof data[k]==='string'&&data[k].trim().length<20));if(!Array.isArray(data.posicoes)||data.posicoes.length!==3)missing.push('posicoes completas');if(!Array.isArray(data.planoPratico)||data.planoPratico.length<3)missing.push('planoPratico completo');if(missing.length)throw new Error(`Seções incompletas: ${[...new Set(missing)].join(', ')}`);return data;}
function localReading(selected,q){const roles=['Clima atual','Ponte de conexão','Próximo passo'];return{visaoGeral:`A combinação ${selected.map(c=>c[1]).join(' + ')} descreve uma jornada em que ${selected[0][3]}, ${selected[1][3]} e ${selected[2][3]} precisam ser lidos em sequência. O primeiro símbolo mostra a atmosfera percebida; o segundo indica como construir ligação; o terceiro converte a leitura em uma atitude concreta.\n\nNo contexto da partida, ${state.answered} respostas e ${state.insights.length} insights sugerem que a melhor interpretação é aquela que transforma símbolos em conversa verificável entre vocês.`,respostaPergunta:q?`Para a pergunta “${q}”, as cartas não oferecem uma certeza externa. Elas sugerem observar como o tema de ${selected[0][3]} encontra uma ponte em ${selected[1][3]} e pode avançar por meio de ${selected[2][3]}.`:'A leitura aberta indica que a conexão se beneficia de clareza, escuta e um próximo passo pequeno, escolhido pelos dois.',posicoes:selected.map((c,i)=>({posicao:roles[i],carta:c[1],interpretacao:c[4],potencial:`O potencial desta posição está em ${c[3]}.`,sombra:c[5],convite:c[6]})),combinacao:`Em conjunto, ${selected[0][1]} inicia o tema, ${selected[1][1]} mostra a ponte necessária e ${selected[2][1]} pede uma aplicação prática. A qualidade da combinação depende de evitar a sombra de cada carta e confirmar interpretações por meio de diálogo.`,dimensoes:{atracao:'A tiragem pode representar curiosidade e presença, mas não comprova desejo ou intensidade.',carinho:'O carinho aparece como atitude observável, cuidado e disponibilidade.',confianca:'Confiança deve ser avaliada pela constância e pelo respeito aos limites.',comunicacao:'A comunicação é a ferramenta que transforma símbolos em entendimento real.',expectativas:'Expectativas precisam ser nomeadas para não virarem suposições.',intencao:'Intenção só pode ser confirmada por escolhas e conversas diretas.'},pontoAtencao:`Evitem usar a carta ${selected[0][1]} ou qualquer outra como prova sobre o que o outro sente. Usem a leitura para formular perguntas melhores.`,planoPratico:[selected[0][6],selected[1][6],selected[2][6]],perguntaFinal:'Qual parte desta leitura descreve algo observável entre vocês e qual parte ainda precisa de uma conversa direta?'};}
function renderReading(data,meta){const dims=data.dimensoes||{};$('readingSections').innerHTML=`<section class="readingSection"><h4>Visão geral</h4><p>${escapeHtml(data.visaoGeral)}</p></section><section class="readingSection"><h4>Resposta à pergunta</h4><p>${escapeHtml(data.respostaPergunta)}</p></section><section class="readingSection"><h4>As três posições</h4><div class="positionGrid">${data.posicoes.map(p=>`<div class="positionBox"><b>${escapeHtml(p.posicao)} · ${escapeHtml(p.carta)}</b><p>${escapeHtml(p.interpretacao)}</p><p><strong>Potencial:</strong> ${escapeHtml(p.potencial)}</p><p><strong>Sombra:</strong> ${escapeHtml(p.sombra)}</p><p><strong>Convite:</strong> ${escapeHtml(p.convite)}</p></div>`).join('')}</div></section><section class="readingSection"><h4>Combinação das cartas</h4><p>${escapeHtml(data.combinacao)}</p></section><section class="readingSection"><h4>Dimensões da relação</h4><div class="dimensionGrid">${Object.entries({Atração:dims.atracao,Carinho:dims.carinho,Confiança:dims.confianca,Comunicação:dims.comunicacao,Expectativas:dims.expectativas,Intenção:dims.intencao}).map(([k,v])=>`<div class="dimensionBox"><b>${k}</b><p>${escapeHtml(v||'Não analisado.')}</p></div>`).join('')}</div></section><section class="readingSection"><h4>Ponto de atenção</h4><p>${escapeHtml(data.pontoAtencao)}</p></section><section class="readingSection"><h4>Plano prático</h4><ol class="actionList">${data.planoPratico.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ol></section><section class="readingSection"><h4>Pergunta final para o casal</h4><p>${escapeHtml(data.perguntaFinal)}</p></section>`;$('readingMeta').textContent=meta;}
async function generateTarot(selected,q,extra){const model=$('geminiModel').value,lastPrompt=buildTarotContext(selected,q,extra);lastTarotRequest={selected,q,extra};$('reading').classList.remove('hidden');$('readingLoading').classList.remove('hidden');$('readingSections').innerHTML='';$('drawTarot').disabled=true;$('retryTarot').classList.add('hidden');if(!geminiKey){renderReading(localReading(selected,q),'Motor local · conecte a IA para interpretação externa');$('readingEngine').textContent='Motor local';$('readingLoading').classList.add('hidden');$('drawTarot').disabled=false;toast('Leitura local gerada. Conecte o Gemini para a versão por IA.');return;}try{let response=await callGemini(lastPrompt,model,{structured:true,maxOutputTokens:7000,thinkingLevel:'high'});let parsed;try{parsed=parseStructured(response.text);}catch(firstError){const retryPrompt=`A resposta anterior ficou incompleta ou inválida (${firstError.message}). Gere novamente TODAS as seções, sem resumir e obedecendo integralmente ao esquema.\n\n${lastPrompt}`;response=await callGemini(retryPrompt,model,{structured:true,maxOutputTokens:9000,thinkingLevel:'high'});parsed=parseStructured(response.text);}renderReading(parsed,`${model} · término ${response.finishReason} · ${response.usage?.candidatesTokenCount||'—'} tokens de resposta`);$('readingEngine').textContent=model;setAIState('IA conectada','connected');}catch(error){renderReading(localReading(selected,q),`Fallback local · erro: ${error.message}`);$('readingEngine').textContent='Fallback local';$('retryTarot').classList.remove('hidden');setAIState('Erro na última leitura','error');toast('A leitura local foi exibida. Use “Tentar novamente”.');}finally{$('readingLoading').classList.add('hidden');$('drawTarot').disabled=false;}}
function drawTarot(){const selected=shuffle(lenormand).slice(0,3),roles=['Clima atual','Ponte de conexão','Próximo passo'];$('spread').innerHTML=selected.map((c,i)=>`<article class="lenormand"><span class="cardNumber">${String(c[0]).padStart(2,'0')}</span><div class="cardSymbol">${c[2]}</div><div class="cardName">${escapeHtml(c[1])}</div><div class="cardRole">${roles[i]}</div></article>`).join('');generateTarot(selected,$('tarotQuestion').value.trim(),$('tarotContext').value.trim());}
function retryTarot(){if(!lastTarotRequest)return;generateTarot(lastTarotRequest.selected,lastTarotRequest.q,lastTarotRequest.extra);}
function clearTarot(){$('spread').innerHTML='';$('reading').classList.add('hidden');$('retryTarot').classList.add('hidden');lastTarotRequest=null;}

function updateMusicButton(){if(!$('musicToggle'))return;$('musicToggle').textContent=musicPlaying?'Pausar trilha':'Ativar trilha';}
function playMusic(){if(!spotifyController){setMusicStatus('O player ainda está carregando…');return;}try{spotifyController.play();setMusicStatus('Tentando iniciar a playlist…');setTimeout(()=>{if(!musicPlaying)setMusicStatus('O navegador aguardou uma interação. Toque em “Ativar trilha”.','blocked');},1400);}catch{setMusicStatus('Toque em “Ativar trilha” para começar.','blocked');}}
function toggleMusic(){if(!spotifyController){setMusicStatus('Aguarde o carregamento do Spotify.');return;}try{spotifyController.togglePlay();}catch{playMusic();}}
function initSpotify(){window.onSpotifyIframeApiReady=IFrameAPI=>{IFrameAPI.createController($('spotifyEmbed'),{width:'100%',height:152,uri:'spotify:playlist:3OkkVMtZSxmRuD4BIlDQkf'},controller=>{spotifyController=controller;controller.addListener('ready',()=>{setMusicStatus('Playlist pronta. Tentando iniciar automaticamente…');playMusic();if(userInteracted)setTimeout(playMusic,100);});controller.addListener('playback_started',()=>{musicPlaying=true;setMusicStatus('Trilha sonora em reprodução.','playing');updateMusicButton();});controller.addListener('playback_update',event=>{musicPlaying=!event.data.isPaused;updateMusicButton();if(musicPlaying)setMusicStatus('Trilha sonora em reprodução.','playing');});});};const script=document.createElement('script');script.src='https://open.spotify.com/embed/iframe-api/v1';script.async=true;script.onerror=()=>setMusicStatus('Não foi possível carregar o Spotify.','blocked');document.body.appendChild(script);document.addEventListener('pointerdown',()=>{userInteracted=true;if(spotifyController&&!musicPlaying)playMusic();},{once:true,capture:true});document.addEventListener('keydown',()=>{userInteracted=true;if(spotifyController&&!musicPlaying)playMusic();},{once:true,capture:true});}

document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.go==='how'){document.getElementById('how').scrollIntoView({behavior:'smooth'});}else show(b.dataset.go);}));
document.querySelectorAll('#levels .option').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#levels .option').forEach(x=>x.classList.remove('on'));b.classList.add('on');state.level=Number(b.dataset.value);}));
$('startGame').addEventListener('click',startGame);$('exitGame').addEventListener('click',()=>show('setup'));$('answer').addEventListener('click',()=>advance('answered'));$('adapt').addEventListener('click',adaptCurrent);$('skip').addEventListener('click',openSkip);$('saveInsight').addEventListener('click',saveInsight);$('favorite').addEventListener('click',()=>{state.fav=!state.fav;$('favorite').textContent=state.fav?'♥':'♡';$('favorite').classList.toggle('on',state.fav);});
$('newAlternative').addEventListener('click',pickAlternative);$('cancelSkip').addEventListener('click',()=>$('skipModal').classList.add('hidden'));$('acceptAlternative').addEventListener('click',()=>{$('skipModal').classList.add('hidden');advance('skipped');});$('playAgain').addEventListener('click',()=>show('setup'));$('rollDice').addEventListener('click',rollDice);$('saveDice').addEventListener('click',saveDice);$('connectAI').addEventListener('click',connectAI);$('disconnectAI').addEventListener('click',disconnectAI);$('drawTarot').addEventListener('click',drawTarot);$('retryTarot').addEventListener('click',retryTarot);$('clearTarot').addEventListener('click',clearTarot);$('musicToggle').addEventListener('click',toggleMusic);$('kitInfo').addEventListener('click',()=>toast('Use o pacote STL entregue com o projeto.'));
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden');});$('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden');});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));renderAutoContext();initSpotify();