'use strict';
(() => {
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])), text=(id,v,f='')=>{const e=$(id);if(e)e.textContent=String(v??f)}, toggle=(id,on)=>$(id)?.classList.toggle('hidden',!on);
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const rawCards=typeof cards!=='undefined'&&Array.isArray(cards)?cards:[], tarotDeck=typeof lenormand!=='undefined'&&Array.isArray(lenormand)?lenormand:[], iconMap=typeof icons!=='undefined'?icons:{};
const ALT=typeof alternatives!=='undefined'&&Array.isArray(alternatives)&&alternatives.length?alternatives:['Façam um elogio específico um ao outro.','Escolham uma música para este momento.','Inventem uma pergunta nova e respondam os dois.'];
const PHASES=[{id:'abertura',symbol:'○',name:'Abertura',description:'Comecem por temas leves para criar presença.',cats:['conversa']},{id:'descoberta',symbol:'◎',name:'Descoberta',description:'Conheçam preferências e compatibilidade.',cats:['afinidade']},{id:'conexao',symbol:'◇',name:'Conexão',description:'Aprofundem confiança e comunicação.',cats:['vinculo']},{id:'romance',symbol:'♥',name:'Romance',description:'Conversem sobre afeto e proximidade confortável.',cats:['romance','faisca']},{id:'experiencia',symbol:'↗',name:'Experiência',description:'Transformem conversa em atividade compartilhada.',cats:['desafio']}];
const GUIDE={conversa:'Conte um exemplo real e explique por que foi importante.',afinidade:'Diga sua preferência e mostre como aparece na prática.',vinculo:'Fale sobre atitudes concretas no nível confortável.',romance:'Fale sobre suas preferências sem presumir o que o outro sente.',faisca:'Descreva uma forma de proximidade confortável.',desafio:'Conversem antes, adaptem e só realizem com concordância clara.'};
const REASON={conversa:'Cria presença e abre a conversa.',afinidade:'Ajuda a perceber preferências e compatibilidade.',vinculo:'Favorece compreensão emocional.',romance:'Nomeia afeto sem criar obrigação.',faisca:'Explora proximidade com respeito.',desafio:'Transforma conversa em experiência.'};
const CARDS=rawCards.map((c,i)=>({id:`c${i}`,c:c?.c||'conversa',l:Math.max(1,Math.min(3,Number(c?.l)||1)),q:String(c?.q||'Compartilhem algo importante.'),w:String(c?.w||REASON[c?.c]||REASON.conversa),h:String(c?.h||GUIDE[c?.c]||GUIDE.conversa),d:Boolean(c?.d)}));
const DICE={action:['Dar as mãos','Abraço confortável','Contato visual','Dança curta','Carinho nas mãos','Gesto escolhido juntos'],time:['5 segundos','10 segundos','15 segundos','20 segundos','30 segundos','45 segundos'],mood:['divertido','carinhoso','calmo','romântico','criativo','surpresa conjunta']};
const blank=()=>({version:8,p1:'',p2:'',duration:18,level:2,deck:[],index:0,answered:0,skipped:0,favorites:0,spark:0,fav:false,insights:[],favoriteCards:[],phaseStats:{},categories:{},lastDice:'',tarotData:null,tarotCards:[],closing:null,currentView:'home'});
let state=blank(),apiKey='',model='',spotifyController=null;
function save(){try{sessionStorage.setItem('primeira-faisca-v8',JSON.stringify(state))}catch{}}
function restore(){try{const s=JSON.parse(sessionStorage.getItem('primeira-faisca-v8')||'null');if(s?.version===8)state={...blank(),...s}}catch{}}
function toast(m){const e=$('toast');if(!e)return;e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function host(r,m,mode='motor local'){text('hostRole',r);text('hostMessage',m);text('hostMode',mode)}
function current(){return state.deck[state.index]||null}function phase(c=current()){return PHASES.find(p=>p.id===c?.phaseId)||PHASES[0]}
const viewId=v=>`view-${v}`;
function show(view,force=false){if(!force){if(['map','chemistry'].includes(view)&&!state.deck.length)view='setup';if(view==='tarot'&&state.index<state.deck.length)view='session';if(view==='closing'&&!state.tarotData)view='tarot'}document.querySelectorAll('.view').forEach(v=>v.classList.toggle('hidden',v.id!==viewId(view)));state.currentView=view;const labels={home:'Início',setup:'Preparação',session:'Jornada',map:'Mapa',chemistry:'Momento da Química',tarot:'Tarô',closing:'Encerramento',kit:'Kit 3D',credits:'Créditos'};text('globalStep',labels[view]||'Início');const n={home:0,setup:1,session:2,map:3,chemistry:4,tarot:5,closing:6}[view]||0;if($('globalBar'))$('globalBar').style.width=`${n/6*100}%`;if(view==='tarot')renderContext();window.scrollTo({top:0,behavior:'smooth'});save()}
function buildDeck(){const counts=state.duration===12?[3,2,3,2,2]:state.duration===24?[5,5,5,5,4]:[4,4,4,4,2],used=new Set(),deck=[];PHASES.forEach((p,i)=>{const picked=[];for(const c of shuffle(CARDS.filter(c=>p.cats.includes(c.c)&&c.l<=state.level))){if(!used.has(c.id)){picked.push({...c,phaseId:p.id});used.add(c.id)}if(picked.length===counts[i])break}if(picked.length<counts[i])for(const c of shuffle(CARDS.filter(c=>c.l<=state.level))){if(!used.has(c.id)){picked.push({...c,phaseId:p.id});used.add(c.id)}if(picked.length===counts[i])break}deck.push(...picked)});return deck.slice(0,state.duration)}
function start(){const p1=$('p1')?.value.trim(),p2=$('p2')?.value.trim();if(!p1||!p2){text('setupError','Preencha os dois nomes.');return}state={...blank(),p1,p2,duration:Number($('duration')?.value||18),level:Number(document.querySelector('#levels .active')?.dataset.level||2),currentView:'session'};PHASES.forEach(p=>state.phaseStats[p.id]={seen:0,answered:0,skipped:0});state.deck=buildDeck();if(!state.deck.length){text('setupError','O banco de cartas não carregou. Atualize a página.');return}show('session',true);renderCard();host('Dealer da jornada',`A jornada começa em ${phase().name}. ${phase().description}`)}
function renderCard(){if(state.index>=state.deck.length){finish();return}const c=current(),p=phase(c);text('cardCounter',`${state.index+1} de ${state.deck.length}`);if($('sessionBar'))$('sessionBar').style.width=`${state.index/state.deck.length*100}%`;text('phaseSymbol',p.symbol);text('phaseName',p.name);text('phaseDescription',p.description);text('categoryBadge',`${iconMap[c.c]||'◌'} ${c.c}`);text('levelBadge',`Nível ${c.l}`);text('turnLabel',`Vez de ${state.index%2===0?state.p1:state.p2}`);text('questionText',c.q);text('cardReason',c.w||REASON[c.c]);text('answerGuide',c.h||GUIDE[c.c]);text('cardGuidance',c.d?'Atividade compartilhada: adaptem e só realizem com concordância clara.':'Respondam no nível confortável.');if($('insightInput'))$('insightInput').value='';if($('phaseTimeline'))$('phaseTimeline').innerHTML=PHASES.map(x=>`<div class="${x.id===p.id?'active':''}">${x.symbol} ${x.name}</div>`).join('');state.fav=false;text('favorite','♡');save()}
function advance(kind){const c=current();if(!c)return;state.categories[c.c]=(state.categories[c.c]||0)+1;state.phaseStats[c.phaseId].seen++;if(kind==='answered'){state.answered++;state.spark+=c.d?2:1;state.phaseStats[c.phaseId].answered++}else{state.skipped++;state.phaseStats[c.phaseId].skipped++}if(state.fav){state.favorites++;state.favoriteCards.push(c.q)}state.index++;if(state.index>=state.deck.length){finish();return}renderCard();host('Dealer da jornada',phase().description)}
function adapt(){const c=current();if(!c)return;text('questionText',`${c.q.replace(/\?$/,'')} — responda apenas a parte que fizer sentido agora?`);text('answerGuide','Use um exemplo simples e deixe de fora detalhes desconfortáveis.');host('Mediadora','A pergunta foi adaptada sem perder a intenção.')}
function insight(){const v=$('insightInput')?.value.trim();if(!v){toast('Escreva um insight.');return}state.insights.push(v);$('insightInput').value='';save();toast('Insight guardado.')}
function alternative(){text('alternativeText',ALT[Math.floor(Math.random()*ALT.length)]);toggle('alternativeModal',true)}
function top(){return Object.entries(state.categories).sort((a,b)=>b[1]-a[1])[0]?.[0]||''}
function synthesis(){return`Vocês concluíram ${state.answered} respostas e escolheram ${state.skipped} alternativas. ${top()?`O tema mais presente foi ${top()}. `:''}${state.insights.length?`${state.insights.length} insights foram guardados. `:''}Agora a conversa será transformada em um Momento da Química antes da leitura final.`}
function finish(){text('answeredMetric',state.answered);text('skippedMetric',state.skipped);text('favoriteMetric',state.favorites);text('sparkMetric',state.spark);if($('phaseSummary'))$('phaseSummary').innerHTML=PHASES.map(p=>{const x=state.phaseStats[p.id]||{};return`<div class="summaryRow"><b>${p.symbol} ${p.name}</b><span>${x.answered||0} respondidas · ${x.skipped||0} alternativas</span></div>`}).join('');if($('insightSummary'))$('insightSummary').innerHTML=state.insights.length?state.insights.map(i=>`<div class="insightPill">${esc(i)}</div>`).join(''):'<p class="microcopy">Nenhum insight registrado.</p>';text('journeySynthesis',synthesis());show('map',true);host('Diretora da experiência','A jornada foi organizada. Agora vem o Momento da Química.')}
function roll(){const a=Math.floor(Math.random()*6),t=Math.floor(Math.random()*6),m=Math.floor(Math.random()*6),set=(id,n,v)=>{const e=$(id);if(e){e.querySelector('span').textContent=n;e.querySelector('b').textContent=v}};set('dieAction',a+1,DICE.action[a]);set('dieTime',t+1,DICE.time[t]);set('dieMood',m+1,DICE.mood[m]);text('diceCombo',`${DICE.action[a]} por ${DICE.time[t]}, em clima ${DICE.mood[m]}.`);text('diceMeaning','A proposta pode ser aceita, adaptada ou trocada. Ao continuar, será integrada ao Tarô.');text('diceSaved','Momento pronto.');if($('continueTarot'))$('continueTarot').disabled=false;host('Anfitriã da Química',`O momento sorteado foi: ${DICE.action[a]} por ${DICE.time[t]}, em clima ${DICE.mood[m]}.`)}
function toTarot(){const combo=$('diceCombo')?.textContent.trim();if(!combo||/Role os dados/i.test(combo)){toast('Role os dados antes de continuar.');return}state.lastDice=combo;text('diceSaved','✓ Momento guardado. Abrindo o Tarô…');save();show('tarot',true)}
function context(){return`Participantes: ${state.p1} e ${state.p2}. Respondidas: ${state.answered}. Alternativas: ${state.skipped}. Insights: ${state.insights.join(' | ')||'nenhum'}. Momento: ${state.lastDice||'não realizado'}.`}
function renderContext(){text('autoContext',`Contexto automático: ${state.p1||'Pessoa 1'} + ${state.p2||'Pessoa 2'} · ${state.answered} respondidas · ${state.skipped} alternativas${state.lastDice?' · momento guardado':''}.`)}
function localTarot(sel,q){const roles=['Clima atual','Ponte de conexão','Próximo passo'];return{visaoGeral:`As cartas ${sel.map(c=>c[1]).join(', ')} formam uma sequência simbólica. A primeira mostra o clima percebido, a segunda indica como criar ligação e a terceira propõe um próximo passo.\n\nA leitura considera o percurso do jogo, mas não afirma conhecer sentimentos ocultos nem prever fatos.`,respostaPergunta:q?`Sobre “${q}”, as cartas convidam a observar como ${sel[0][3]} encontra apoio em ${sel[1][3]} e pode ser transformado em ${sel[2][3]}. A resposta concreta depende da conversa entre vocês.`:'A tiragem recomenda transformar curiosidade em comunicação clara.',posicoes:sel.map((c,i)=>({posicao:roles[i],carta:c[1],interpretacao:c[4],potencial:`Potencial: ${c[3]}.`,sombra:c[5],convite:c[6]})),combinacao:`${sel[0][1]} abre o tema, ${sel[1][1]} mostra a ponte e ${sel[2][1]} orienta a ação.`,dimensoes:{atracao:'Pode haver curiosidade, mas a tiragem não comprova intensidade.',carinho:'Carinho aparece em cuidado observável.',confianca:'Confiança cresce por constância e limites.',comunicacao:'A comunicação transforma impressão em entendimento.',expectativas:'Expectativas precisam ser nomeadas.',intencao:'Intenção só pode ser confirmada por escolhas.'},pontoAtencao:'Não usem as cartas como prova sobre o que o outro sente.',planoPratico:sel.map(c=>c[6]).slice(0,3),perguntaFinal:'Qual parte corresponde a algo observável e qual ainda precisa ser conversada?'}}
function renderReading(d,meta='Motor local inteligente'){const p=v=>esc(v).replace(/\n\n/g,'</p><p>').replace(/\n/g,'<br>');if($('readingSections'))$('readingSections').innerHTML=`<section class="readingSection"><h4>Visão geral</h4><p>${p(d.visaoGeral)}</p></section><section class="readingSection"><h4>Resposta</h4><p>${p(d.respostaPergunta)}</p></section><section class="readingSection"><h4>As três posições</h4>${d.posicoes.map(x=>`<article class="positionBox"><b>${esc(x.posicao)} · ${esc(x.carta)}</b><p>${p(x.interpretacao)}</p><p>${p(x.potencial)}</p><p><strong>Sombra:</strong> ${p(x.sombra)}</p><p><strong>Convite:</strong> ${p(x.convite)}</p></article>`).join('')}</section><section class="readingSection"><h4>Combinação</h4><p>${p(d.combinacao)}</p></section><section class="readingSection"><h4>Dimensões</h4>${Object.entries(d.dimensoes).map(([k,v])=>`<p><strong>${esc(k)}:</strong> ${p(v)}</p>`).join('')}</section><section class="readingSection"><h4>Ponto de atenção</h4><p>${p(d.pontoAtencao)}</p></section><section class="readingSection"><h4>Plano prático</h4><ol>${d.planoPratico.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></section><section class="readingSection"><h4>Pergunta final</h4><p>${p(d.perguntaFinal)}</p></section>`;text('readingMeta',meta);text('readingEngine',meta);toggle('reading',true);toggle('toClosing',true)}
function draw(){const b=$('drawTarot');if(b){b.disabled=true;b.textContent='Embaralhando…'}try{if(tarotDeck.length<3)throw new Error('O Baralho Cigano não carregou.');const sel=shuffle(tarotDeck).slice(0,3),roles=['Clima atual','Ponte de conexão','Próximo passo'];state.tarotCards=sel;if($('spread'))$('spread').innerHTML=sel.map((c,i)=>`<article class="lenormand"><span class="number">${String(c[0]).padStart(2,'0')}</span><div class="symbol">${c[2]}</div><h3>${esc(c[1])}</h3><small>${roles[i]}</small></article>`).join('');const q=$('tarotQuestion')?.value.trim()||'',local=localTarot(sel,q);state.tarotData=local;renderReading(local);save();$('spread')?.scrollIntoView({behavior:'smooth',block:'center'});if(apiKey)enhance(sel,q).catch(e=>toast(friendly(e)))}catch(e){toast(e.message)}finally{if(b){b.disabled=false;b.textContent='Tirar três cartas e interpretar'}}}
async function enhance(sel,q){text('readingMeta','Aprofundando com IA…');const ans=await gemini(`Faça uma leitura Lenormand completa em português. Pergunta: ${q||'leitura aberta'}. Contexto: ${context()}. Cartas: ${sel.map(c=>`${c[1]} (${c[3]}, potência ${c[4]}, sombra ${c[5]})`).join(' | ')}. Não afirme sentimentos ocultos como fatos.`,7000);$('readingSections')?.insertAdjacentHTML('afterbegin',`<section class="readingSection"><h4>Leitura aprofundada pela IA</h4><p>${esc(ans).replace(/\n/g,'<br>')}</p></section>`);text('readingMeta',`Gemini · ${model}`);text('readingEngine',model)}
function localClosing(){return{clareza:'A experiência mostrou os temas que receberam mais atenção.',conversaPendente:'Escolham apenas um tema que ainda merece esclarecimento.',proximoPasso:'Combinem uma atividade simples e uma data realista.',memoriaFinal:state.lastDice?`Guardem como símbolo: ${state.lastDice}`:'Escolham uma música ou frase para representar o encontro.',fraseFinal:'A experiência termina, a conversa continua.',instrucaoFinal:'Cada pessoa diz uma coisa de que gostou e uma que gostaria de repetir.'}}
function renderClosing(d){if($('closingGrid'))$('closingGrid').innerHTML=`<article class="closingCard"><h3>O que ficou claro</h3><p>${esc(d.clareza)}</p></article><article class="closingCard"><h3>Conversa pendente</h3><p>${esc(d.conversaPendente)}</p></article><article class="closingCard"><h3>Próximo passo</h3><p>${esc(d.proximoPasso)}</p></article><article class="closingCard"><h3>Memória final</h3><p>${esc(d.memoriaFinal)}</p></article>`;text('finalPhrase',d.fraseFinal);text('finalInstruction',d.instrucaoFinal)}
function closing(){const d=localClosing();state.closing=d;renderClosing(d);show('closing',true);save()}
function friendly(e){const m=String(e?.message||e);if(/quota|429|rate.?limit|resource_exhausted/i.test(m))return'A cota gratuita da IA está temporariamente esgotada. O motor local continua funcionando.';if(/abort|timeout/i.test(m))return'A IA demorou demais. O motor local permaneceu ativo.';return'A IA externa não respondeu. O motor local permaneceu ativo.'}
async function gemini(prompt,max=2000){if(!apiKey||!model)throw new Error('IA não conectada.');const c=new AbortController(),t=setTimeout(()=>c.abort(),60000);try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':apiKey},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{maxOutputTokens:max}}),signal:c.signal});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`Erro ${r.status}`);const out=d?.candidates?.[0]?.content?.parts?.map(p=>p.text||'').join('').trim();if(!out)throw new Error('Resposta vazia.');return out}finally{clearTimeout(t)}}
async function connect(){const key=$('geminiKey')?.value.trim();if(!key||key.length<20){text('aiState','Chave inválida');return}text('aiState','Conectando…');try{const r=await fetch('https://generativelanguage.googleapis.com/v1beta/models?pageSize=100',{headers:{'x-goog-api-key':key}}),d=await r.json();if(!r.ok)throw new Error(d?.error?.message||'Falha ao listar modelos.');const ms=(d.models||[]).filter(m=>(m.supportedGenerationMethods||[]).includes('generateContent')&&/gemini/i.test(m.name||'')&&!/image|audio|tts|live/i.test(m.name||''));if(!ms.length)throw new Error('Nenhum modelo compatível.');apiKey=key;model=(ms.find(m=>/flash/i.test(m.name))||ms[0]).name.replace(/^models\//,'');if($('geminiModel'))$('geminiModel').innerHTML=ms.map(m=>`<option value="${esc(m.name.replace(/^models\//,''))}">${esc(m.displayName||m.name)}</option>`).join('');$('geminiModel').value=model;text('aiState',`Conectado a ${model}`);text('aiTopStatus','Gemini ativo');toast('IA conectada.')}catch(e){apiKey='';model='';text('aiState',friendly(e))}}
function disconnect(){apiKey='';model='';text('aiState','Motor local ativo');text('aiTopStatus','Motor local')}
function action(name){switch(name){case'go-home':show('home');break;case'go-setup':show('setup');break;case'go-current':show(state.currentView||'home',true);break;case'go-kit':show('kit');break;case'go-credits':show('credits');break;case'go-chemistry':show('chemistry');break;case'scroll-instructions':$('instructions')?.scrollIntoView({behavior:'smooth'});break;case'start':start();break;case'answer':advance('answered');break;case'alternative':alternative();break;case'adapt':adapt();break;case'favorite':state.fav=!state.fav;text('favorite',state.fav?'♥':'♡');break;case'save-insight':insight();break;case'new-alternative':alternative();break;case'use-alternative':toggle('alternativeModal',false);advance('skipped');break;case'close-alternative':toggle('alternativeModal',false);break;case'roll':roll();break;case'continue-tarot':toTarot();break;case'draw-tarot':draw();break;case'retry-tarot':draw();break;case'clear-tarot':if($('spread'))$('spread').innerHTML='';toggle('reading',false);toggle('toClosing',false);state.tarotData=null;break;case'build-closing':closing();break;case'restart':sessionStorage.removeItem('primeira-faisca-v8');state=blank();show('home',true);break;case'connect-ai':connect();break;case'disconnect-ai':disconnect();break;case'open-ai':show('setup');setTimeout(()=>$('aiPanel')?.scrollIntoView({behavior:'smooth'}),100);break;case'open-host':toggle('hostModal',true);break;case'close-host':toggle('hostModal',false);break;case'ask-host':text('hostReply','A sequência correta é preparação, jornada, mapa, Momento da Química, Tarô e encerramento.');break;case'refine-synthesis':text('journeySynthesis',synthesis());toast('Síntese atualizada.');break;case'refine-closing':closing();break;case'toggle-music':if(spotifyController)spotifyController.togglePlay();break}}
function bind(){document.addEventListener('click',e=>{const t=e.target.closest('[data-action]');if(!t)return;e.preventDefault();action(t.dataset.action)});document.querySelectorAll('#levels button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#levels button').forEach(x=>x.classList.remove('active'));b.classList.add('active')}));$('geminiModel')?.addEventListener('change',e=>model=e.target.value)}
function spotify(){window.onSpotifyIframeApiReady=API=>API.createController($('spotifyEmbed'),{width:'100%',height:152,uri:'spotify:playlist:3OkkVMtZSxmRuD4BIlDQkf'},controller=>{spotifyController=controller;controller.addListener('ready',()=>text('musicStatus','Playlist pronta.'))});const s=document.createElement('script');s.src='https://open.spotify.com/embed/iframe-api/v1';s.async=true;s.onerror=()=>text('musicStatus','Não foi possível carregar o Spotify.');document.body.appendChild(s)}
function audit(){const actions=[...document.querySelectorAll('[data-action]')].map(e=>e.dataset.action),known=new Set(['go-home','go-setup','go-current','go-kit','go-credits','go-chemistry','scroll-instructions','start','answer','alternative','adapt','favorite','save-insight','new-alternative','use-alternative','close-alternative','roll','continue-tarot','draw-tarot','retry-tarot','clear-tarot','build-closing','restart','connect-ai','disconnect-ai','open-ai','open-host','close-host','ask-host','refine-synthesis','refine-closing','toggle-music']),unknown=[...new Set(actions.filter(a=>!known.has(a)))],ids={};document.querySelectorAll('[id]').forEach(e=>ids[e.id]=(ids[e.id]||0)+1);const dup=Object.entries(ids).filter(([,n])=>n>1).map(([id])=>id);console.info('Auditoria v8',{unknownActions:unknown,duplicateIds:dup,cards:CARDS.length,tarot:tarotDeck.length});if(unknown.length||dup.length)host('Auditoria','Uma inconsistência foi detectada. Atualize a página.','modo de segurança')}
function restoreUI(){if(state.p1)$('p1').value=state.p1;if(state.p2)$('p2').value=state.p2;if(state.currentView==='session'&&state.deck.length)renderCard();if(state.tarotData)renderReading(state.tarotData,'Sessão restaurada');if(state.closing)renderClosing(state.closing);show(state.currentView||'home',true)}
restore();bind();audit();restoreUI();spotify();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
})();