function tarotSystem(){return `${hostSystem('cigana simbólica e intérprete técnica do Lenormand')} Diferencie atração, carinho, confiança, comunicação, expectativa e intenção. Não repita a mesma ideia em seções diferentes. Preencha todas as seções com profundidade e clareza.`;}
function buildTarotPrompt(selected,question,extra){
  const roles=['Clima atual','Ponte de conexão','Próximo passo'];const cardText=selected.map((card,index)=>`${roles[index]} — ${card[1]}: núcleo=${card[3]}; potência=${card[4]}; sombra=${card[5]}; convite=${card[6]}`).join('\n');
  return `${journeyContext()}\nContexto adicional: ${extra||'não informado'}.\nPergunta principal: ${question||'O que esta experiência ajuda o casal a compreender sobre a conexão construída?'}.\n\nCartas sorteadas:\n${cardText}\n\nProduza uma leitura extensa e específica. A visão geral deve ter pelo menos dois parágrafos. Analise cada posição, depois a combinação. Diferencie todas as dimensões. Termine com 3 a 5 ações realistas e uma pergunta concreta. Não use fatalismo nem afirme conhecer sentimentos ocultos.`;
}
function validateTarot(data){const keys=['visaoGeral','respostaPergunta','posicoes','combinacao','dimensoes','pontoAtencao','planoPratico','perguntaFinal'];const missing=keys.filter(key=>data?.[key]==null);if(!Array.isArray(data?.posicoes)||data.posicoes.length!==3)missing.push('três posições');if(!Array.isArray(data?.planoPratico)||data.planoPratico.length<3)missing.push('plano prático');if(String(data?.visaoGeral||'').length<180)missing.push('visão geral robusta');if(missing.length)throw new Error(`Leitura incompleta: ${[...new Set(missing)].join(', ')}`);return data;}
function localTarot(selected,question){const roles=['Clima atual','Ponte de conexão','Próximo passo'];return{visaoGeral:`A combinação ${selected.map(card=>card[1]).join(' + ')} forma uma sequência simbólica. A primeira carta descreve a atmosfera percebida; a segunda mostra a ponte necessária; a terceira converte o tema em um próximo passo.\n\nO percurso do jogo acrescenta dados observáveis: ${state.answered} respostas, ${state.skipped} alternativas e ${state.insights.length} insights. Esses sinais não diagnosticam a relação, mas ajudam a decidir quais temas merecem conversa direta.`,respostaPergunta:question?`Sobre “${question}”, as cartas sugerem observar como ${selected[0][3]} encontra apoio em ${selected[1][3]} e pode ser transformado em ${selected[2][3]}. A resposta real depende da conversa entre vocês.`:'A leitura aberta recomenda transformar curiosidade em comunicação e escolher um passo pequeno que os dois reconheçam como confortável.',posicoes:selected.map((card,index)=>({posicao:roles[index],carta:card[1],interpretacao:card[4],potencial:`O potencial está em ${card[3]}.`,sombra:card[5],convite:card[6]})),combinacao:`${selected[0][1]} abre o tema, ${selected[1][1]} mostra a forma de ligação e ${selected[2][1]} orienta a aplicação. A combinação funciona melhor quando o potencial de cada carta é confirmado por atitudes observáveis.`,dimensoes:{atracao:'Pode haver curiosidade e presença, mas as cartas não comprovam intensidade de desejo.',carinho:'Carinho deve ser reconhecido em cuidado, atenção e disponibilidade.',confianca:'Confiança cresce por constância, clareza e respeito aos limites.',comunicacao:'A comunicação transforma símbolos e impressões em entendimento verificável.',expectativas:'Expectativas precisam ser nomeadas para não virarem suposições.',intencao:'Intenção só pode ser confirmada por escolhas e conversas diretas.'},pontoAtencao:'Não usem a leitura como prova sobre o que o outro sente. Usem cada símbolo para formular perguntas melhores.',planoPratico:selected.map(card=>card[6]).slice(0,3),perguntaFinal:'Qual parte desta leitura corresponde a algo observável entre vocês e qual parte ainda precisa ser conversada?'};}
function renderReading(data,meta){
  const dims=data.dimensoes||{};const paragraphs=text=>escapeHtml(text).replace(/\n\n/g,'</p><p>').replace(/\n/g,'<br>');
  $('readingSections').innerHTML=`<section class="readingSection"><h4>Visão geral</h4><p>${paragraphs(data.visaoGeral)}</p></section><section class="readingSection"><h4>Resposta à pergunta</h4><p>${paragraphs(data.respostaPergunta)}</p></section><section class="readingSection"><h4>As três posições</h4><div class="positionGrid">${data.posicoes.map(item=>`<div class="positionBox"><b>${escapeHtml(item.posicao)} · ${escapeHtml(item.carta)}</b><p>${paragraphs(item.interpretacao)}</p><p><strong>Potencial:</strong> ${paragraphs(item.potencial)}</p><p><strong>Sombra:</strong> ${paragraphs(item.sombra)}</p><p><strong>Convite:</strong> ${paragraphs(item.convite)}</p></div>`).join('')}</div></section><section class="readingSection"><h4>Combinação</h4><p>${paragraphs(data.combinacao)}</p></section><section class="readingSection"><h4>Dimensões da relação</h4><div class="dimensionGrid">${Object.entries({Atração:dims.atracao,Carinho:dims.carinho,Confiança:dims.confianca,Comunicação:dims.comunicacao,Expectativas:dims.expectativas,Intenção:dims.intencao}).map(([key,value])=>`<div class="dimensionBox"><b>${key}</b><p>${paragraphs(value||'Não analisado.')}</p></div>`).join('')}</div></section><section class="readingSection"><h4>Ponto de atenção</h4><p>${paragraphs(data.pontoAtencao)}</p></section><section class="readingSection"><h4>Plano prático</h4><ol class="actionList">${data.planoPratico.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ol></section><section class="readingSection"><h4>Pergunta final</h4><p>${paragraphs(data.perguntaFinal)}</p></section>`;
  safeText('readingMeta',meta);
}
async function generateTarot(selected,question,extra){
  lastTarotRequest={selected,question,extra};$('reading').classList.remove('hidden');$('readingLoading').classList.remove('hidden');$('readingSections').innerHTML='';$('drawTarot').disabled=true;$('retryTarot').classList.add('hidden');
  const fallback=localTarot(selected,question);if(!geminiKey){renderReading(fallback,'Motor local · conecte o Gemini para aprofundar');safeText('readingEngine','Motor local');$('readingLoading').classList.add('hidden');$('drawTarot').disabled=false;return;}
  setHost('Cigana simbólica','As cartas e o percurso estão sendo organizados em uma leitura estruturada…','Gemini pensando');
  try{
    const prompt=buildTarotPrompt(selected,question,extra);let response=await callGeminiRaw(prompt,{schema:tarotSchema,maxOutputTokens:Math.min(10000,outputLimit(selectedModel())),thinkingLevel:'high',system:tarotSystem()});let parsed;
    try{parsed=validateTarot(parseJSONLoose(response.text));}catch(firstError){response=await callGeminiRaw(`A resposta anterior ficou incompleta: ${firstError.message}. Gere novamente todas as seções, sem resumir.\n\n${prompt}`,{schema:tarotSchema,maxOutputTokens:Math.min(12000,outputLimit(selectedModel())),thinkingLevel:'high',system:tarotSystem()});parsed=validateTarot(parseJSONLoose(response.text));}
    renderReading(parsed,`${selectedModel()} · ${response.finishReason} · ${response.usage?.candidatesTokenCount||'—'} tokens`);safeText('readingEngine',selectedModel());setHost('Cigana simbólica','A leitura foi concluída com oito blocos e um plano prático.','Gemini conectado');
  }catch(error){renderReading(fallback,`Fallback local · ${error.message}`);safeText('readingEngine','Fallback local');$('retryTarot').classList.remove('hidden');setHost('Cigana simbólica','A leitura local foi preservada; as mesmas cartas podem ser reenviadas à IA.','fallback local');}
  finally{$('readingLoading').classList.add('hidden');$('drawTarot').disabled=false;}
}
function drawTarot(){if(LENORMAND.length<3){toast('Baralho Cigano indisponível.');return;}const selected=shuffle(LENORMAND).slice(0,3),roles=['Clima atual','Ponte de conexão','Próximo passo'];$('spread').innerHTML=selected.map((card,index)=>`<article class="lenormand"><span class="cardNumber">${String(card[0]).padStart(2,'0')}</span><div class="cardSymbol">${card[2]}</div><div class="cardName">${escapeHtml(card[1])}</div><div class="cardRole">${roles[index]}</div></article>`).join('');generateTarot(selected,$('tarotQuestion').value.trim(),$('tarotContext').value.trim());}
function retryTarot(){if(lastTarotRequest)generateTarot(lastTarotRequest.selected,lastTarotRequest.question,lastTarotRequest.extra);}
function clearTarot(){$('spread').innerHTML='';$('reading').classList.add('hidden');$('retryTarot').classList.add('hidden');lastTarotRequest=null;}

