async function listModels(key){const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models?pageSize=1000',{headers:{'x-goog-api-key':key}});const data=await response.json();if(!response.ok)throw new Error(data?.error?.message||`Erro ${response.status}`);return(data.models||[]).filter(m=>{const methods=m.supportedGenerationMethods||m.supportedActions||[];return methods.includes('generateContent')&&/gemini/i.test(m.name||'')});}
function modelId(m){return String(m.name||'').replace(/^models\//,'');}
function rankModel(m){const id=modelId(m);let s=0;if(id==='gemini-3.6-flash')s+=100;if(id==='gemini-3.5-flash')s+=90;if(/flash/i.test(id))s+=40;if(/lite/i.test(id))s-=25;if(/preview|exp/i.test(id))s-=10;if(/image|audio|tts|live/i.test(id))s-=200;return s;}
function chosenModel(){return $('geminiModel').value||'';}
async function connectAI(){const key=$('geminiKey').value.trim();if(key.length<20){setAIStatus('Chave inválida');return;}geminiKey=key;setAIStatus('Consultando modelos…');$('connectAI').disabled=true;try{modelMeta=(await listModels(key)).filter(m=>rankModel(m)>-100).sort((a,b)=>rankModel(b)-rankModel(a)).slice(0,15);if(!modelMeta.length)throw new Error('Nenhum modelo compatível encontrado.');$('geminiModel').innerHTML=modelMeta.map((m,i)=>`<option value="${escapeHtml(modelId(m))}" ${i===0?'selected':''}>${escapeHtml(m.displayName||modelId(m))}</option>`).join('');await aiText('Responda somente com CONECTADO.',{role:'verificador',thinking:'minimal',max:40});$('geminiKey').value='';setAIStatus(`Conectado a ${chosenModel()}`,true);host('Dealer da experiência','A IA está pronta para mediar, narrar, interpretar e construir o encerramento.','Gemini conectado');toast('Gemini conectado.');}catch(error){geminiKey='';modelMeta=[];setAIStatus(`Falha: ${error.message}`);toast('Não foi possível conectar.');}finally{$('connectAI').disabled=false;}}
function disconnectAI(){geminiKey='';modelMeta=[];$('geminiModel').innerHTML='<option value="">Conecte para listar modelos</option>';setAIStatus('Não conectado');host('Dealer da experiência','O site continua com inteligência local e fallbacks completos.','modo local');}
function interactionText(data){const out=[];for(const step of data?.steps||[]){if(step?.type==='model_output')for(const c of step.content||[])if(c?.type==='text'&&c.text)out.push(c.text);}return out.join('').trim();}
async function callInteractions(prompt,{schema=null,role='anfitriã',thinking='medium',max=2000}={}){const body={model:chosenModel(),store:false,input:prompt,system_instruction:roleInstruction(role),generation_config:{thinking_level:thinking,max_output_tokens:max}};if(schema)body.response_format={type:'text',mime_type:'application/json',schema};const response=await fetch('https://generativelanguage.googleapis.com/v1beta/interactions',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':geminiKey},body:JSON.stringify(body)});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data?.error?.message||`Interactions ${response.status}`);const result=interactionText(data);if(!result)throw new Error('Interactions não retornou texto.');return{result,meta:`Interactions · ${data.status||'completed'} · ${data.usage?.total_output_tokens||'—'} tokens`};}
async function callGenerateContent(prompt,{schema=null,role='anfitriã',thinking='medium',max=2000}={}){const generationConfig={maxOutputTokens:max,thinkingConfig:{thinkingLevel:thinking}};if(schema){generationConfig.responseMimeType='application/json';generationConfig.responseJsonSchema=schema;}const body={systemInstruction:{parts:[{text:roleInstruction(role)}]},contents:[{role:'user',parts:[{text:prompt}]}],generationConfig};const response=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(chosenModel())}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':geminiKey},body:JSON.stringify(body)});let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data?.error?.message||`generateContent ${response.status}`);const candidate=data?.candidates?.[0],result=candidate?.content?.parts?.map(p=>p.text||'').join('').trim();if(!result)throw new Error('generateContent não retornou texto.');return{result,meta:`generateContent · ${candidate.finishReason||'—'} · ${data.usageMetadata?.candidatesTokenCount||'—'} tokens`};}
async function aiRequest(prompt,options={}){if(!geminiKey||!chosenModel())throw new Error('Gemini não conectado.');try{return await callInteractions(prompt,options);}catch(first){try{return await callGenerateContent(prompt,options);}catch(second){throw new Error(`${first.message}; reserva: ${second.message}`);}}}
function parseJSON(raw){return JSON.parse(String(raw).trim().replace(/^```json\s*/i,'').replace(/^```/,'').replace(/```$/,'').trim());}
function validateRequired(data,schema){for(const key of schema.required||[])if(data?.[key]===undefined||data?.[key]===null||String(data[key]).trim()==='')throw new Error(`Resposta sem ${key}.`);return data;}
async function aiStructured(prompt,schema,options={}){let response=await aiRequest(prompt,{...options,schema});try{return validateRequired(parseJSON(response.result),schema);}catch(first){response=await aiRequest(`A resposta anterior ficou inválida: ${first.message}. Gere novamente todos os campos, sem resumir.\n\n${prompt}`,{...options,schema,max:Math.min((options.max||2000)*1.5,14000)});return validateRequired(parseJSON(response.result),schema);}}
async function aiText(prompt,options={}){return(await aiRequest(prompt,options)).result;}
