function updateMusicButton(){if($('musicToggle'))$('musicToggle').textContent=musicPlaying?'Pausar trilha':'Ativar trilha';}
function playMusic(){if(!spotifyController){setMusicStatus('O player ainda está carregando…');return;}try{spotifyController.play();setMusicStatus('Tentando iniciar a playlist…');setTimeout(()=>{if(!musicPlaying)setMusicStatus('O navegador aguardou uma interação. Toque em “Ativar trilha”.','blocked');},1400);}catch{setMusicStatus('Toque em “Ativar trilha” para começar.','blocked');}}
function toggleMusic(){if(!spotifyController){setMusicStatus('Aguarde o carregamento do Spotify.');return;}try{spotifyController.togglePlay();}catch{playMusic();}}
function initSpotify(){window.onSpotifyIframeApiReady=IFrameAPI=>{IFrameAPI.createController($('spotifyEmbed'),{width:'100%',height:152,uri:'spotify:playlist:3OkkVMtZSxmRuD4BIlDQkf'},controller=>{spotifyController=controller;controller.addListener('ready',()=>{setMusicStatus('Playlist pronta. Tentando iniciar automaticamente…');playMusic();if(userInteracted)setTimeout(playMusic,100);});controller.addListener('playback_started',()=>{musicPlaying=true;setMusicStatus('Trilha em reprodução.','playing');updateMusicButton();});controller.addListener('playback_update',event=>{musicPlaying=!event.data.isPaused;updateMusicButton();if(musicPlaying)setMusicStatus('Trilha em reprodução.','playing');});});};const script=document.createElement('script');script.src='https://open.spotify.com/embed/iframe-api/v1';script.async=true;script.onerror=()=>setMusicStatus('Não foi possível carregar o Spotify.','blocked');document.body.appendChild(script);document.addEventListener('pointerdown',()=>{userInteracted=true;if(spotifyController&&!musicPlaying)playMusic();},{once:true,capture:true});document.addEventListener('keydown',()=>{userInteracted=true;if(spotifyController&&!musicPlaying)playMusic();},{once:true,capture:true});}

function openModal(id){$(id)?.classList.remove('hidden');}
function closeModal(id){$(id)?.classList.add('hidden');}
function bindEvents(){
  document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>show(button.dataset.view)));
  document.querySelectorAll('[data-go]').forEach(button=>button.addEventListener('click',()=>show(button.dataset.go)));
  document.querySelectorAll('[data-scroll]').forEach(button=>button.addEventListener('click',()=>$(button.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
  document.querySelectorAll('#levels .option').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('#levels .option').forEach(item=>item.classList.remove('on'));button.classList.add('on');}));
  $('startGame').addEventListener('click',startGame);$('exitGame').addEventListener('click',()=>show('setup'));$('answer').addEventListener('click',()=>advance('answered'));$('adapt').addEventListener('click',adaptCurrent);$('skip').addEventListener('click',openSkip);$('favorite').addEventListener('click',()=>{state.fav=!state.fav;$('favorite').textContent=state.fav?'♥':'♡';$('favorite').classList.toggle('on',state.fav);});$('saveInsight').addEventListener('click',saveInsight);
  $('newAlternative').addEventListener('click',pickAlternative);$('cancelSkip').addEventListener('click',()=>closeModal('skipModal'));$('acceptAlternative').addEventListener('click',()=>{closeModal('skipModal');advance('skipped');});
  $('playAgain').addEventListener('click',()=>show('setup'));$('generateSynthesis').addEventListener('click',generateSynthesis);$('rollDice').addEventListener('click',rollDice);$('saveDice').addEventListener('click',saveDice);
  $('drawTarot').addEventListener('click',drawTarot);$('retryTarot').addEventListener('click',retryTarot);$('clearTarot').addEventListener('click',clearTarot);
  $('openAIConfig').addEventListener('click',()=>{show('tarot');setTimeout(()=>document.querySelector('.aiSetup')?.scrollIntoView({behavior:'smooth'}),80);});$('connectAI').addEventListener('click',connectAI);$('disconnectAI').addEventListener('click',disconnectAI);
  $('askHost').addEventListener('click',()=>openModal('hostModal'));$('closeHost').addEventListener('click',()=>closeModal('hostModal'));$('sendHostQuestion').addEventListener('click',askHostQuestion);
  $('musicToggle').addEventListener('click',toggleMusic);$('kitInfo').addEventListener('click',()=>toast('Use o pacote STL entregue junto ao projeto.'));
  document.querySelectorAll('.modal').forEach(modal=>modal.addEventListener('click',event=>{if(event.target===modal)modal.classList.add('hidden');}));
  window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;$('installBtn').classList.remove('hidden');});$('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden');});
}

function boot(){prepareDOM();const report=auditRuntime();bindEvents();renderAutoContext();viewHostMessage('home');initSpotify();if(report.duplicates.length||report.missing.length)setHost('Auditoria do sistema','Uma inconsistência estrutural foi detectada e o modo de segurança está ativo.','auditoria');if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));}
boot();
