'use strict';

const $=id=>document.getElementById(id);
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const title=s=>s?String(s).charAt(0).toUpperCase()+String(s).slice(1):'';
const shuffle=input=>{const a=[...input];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
const escapeHtml=(value='')=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=(id,value,fallback='')=>{const el=$(id);if(!el)return;const final=value!==undefined&&value!==null&&String(value).trim()!==''?value:fallback;el.textContent=String(final||'Orientação indisponível.').trim();};
const VIEWS=['home','setup','session','map','ritual','tarot','closing','kit','credits'];
const VIEW_STEP={home:0,setup:1,session:2,map:3,ritual:4,tarot:5,closing:6,kit:0,credits:0};
const STEP_LABEL=['Início','Preparação','Jornada','Mapa','Ritual','Tarô','Encerramento'];
const PHASES=[
 {id:'abertura',symbol:'○',name:'Abertura',description:'Reduzir tensão, criar presença e começar por temas simples.',cats:['conversa']},
 {id:'descoberta',symbol:'◎',name:'Descoberta',description:'Entender hábitos, preferências e compatibilidade prática.',cats:['afinidade']},
 {id:'conexao',symbol:'◇',name:'Conexão',description:'Aprofundar confiança, apoio, limites e segurança emocional.',cats:['vinculo']},
 {id:'romance',symbol:'♥',name:'Romance',description:'Nomear afeto, interesse e formas confortáveis de proximidade.',cats:['romance','faisca']},
 {id:'experiencia',symbol:'↗',name:'Experiência',description:'Transformar conversa em uma atividade compartilhada e consensual.',cats:['desafio']}
];
const DEFAULT_REASON={conversa:'A pergunta cria presença e oferece uma entrada simples para a conversa.',afinidade:'A resposta ajuda a perceber preferências e compatibilidade prática.',vinculo:'O tema favorece compreensão emocional e comunicação mais clara.',romance:'A carta nomeia interesse e afeto sem presumir o que a outra pessoa sente.',faisca:'A pergunta explora proximidade e curiosidade de forma respeitosa.',desafio:'A atividade converte conversa em uma pequena experiência compartilhada.'};
const DEFAULT_GUIDE={conversa:'Escolha um exemplo específico, conte o que aconteceu e explique por que isso foi importante.',afinidade:'Diga sua preferência principal e use uma situação real para mostrar como ela funciona.',vinculo:'Responda apenas no nível confortável, descrevendo atitudes concretas que ajudam ou dificultam.',romance:'Fale sobre sua própria preferência e evite presumir o que a outra pessoa sente.',faisca:'Descreva uma forma de proximidade confortável e as condições que tornam a experiência positiva.',desafio:'Conversem antes, combinem uma versão confortável e só realizem a atividade com concordância clara.'};
const ICONS=typeof icons!=='undefined'?icons:{conversa:'◌',afinidade:'◎',vinculo:'◇',romance:'♥',faisca:'✦',desafio:'↗'};
const RAW_CARDS=typeof cards!=='undefined'&&Array.isArray(cards)?cards:[];
const CARD_BANK=RAW_CARDS.map((c,i)=>({id:`c${i+1}`,c:c?.c||'conversa',l:clamp(Number(c?.l)||1,1,3),q:String(c?.q||'Compartilhem algo que gostariam de compreender melhor.'),w:String(c?.w||DEFAULT_REASON[c?.c]||DEFAULT_REASON.conversa),h:String(c?.h||DEFAULT_GUIDE[c?.c]||DEFAULT_GUIDE.conversa),d:Boolean(c?.d)}));
const ALT_BANK=typeof alternatives!=='undefined'&&Array.isArray(alternatives)&&alternatives.length?alternatives:['Façam um elogio específico um ao outro.','Escolham uma música que represente o momento.','Inventem uma nova pergunta e respondam os dois.','Planejem uma atividade simples para outro dia.'];
const LENORMAND=typeof lenormand!=='undefined'&&Array.isArray(lenormand)?lenormand:[];
const DICE={action:['Dar as mãos','Abraço confortável','Contato visual','Dança curta','Carinho nas mãos','Gesto escolhido juntos'],time:['5 segundos','10 segundos','15 segundos','20 segundos','30 segundos','45 segundos'],mood:['divertido','carinhoso','calmo','romântico','criativo','como surpresa conjunta']};

const emptyState=()=>({version:7,p1:'',p2:'',duration:18,level:2,hostStyle:'elegante',autonomy:'active',deck:[],index:0,answered:0,skipped:0,favorites:0,spark:0,fav:false,categories:{},phaseStats:{},insights:[],favoriteCards:[],lastDice:'',synthesis:'',tarotData:null,tarotCards:[],closing:null,currentView:'home',hostHistory:[],startedAt:null});
let state=emptyState();
let geminiKey='';
let modelMeta=[];
let spotifyController=null,musicPlaying=false,userInteracted=false,deferredPrompt=null,lastTarotRequest=null;

function saveState(){try{sessionStorage.setItem('primeira-faisca-v7',JSON.stringify({...state,geminiKey:undefined}));}catch{}}
function restoreState(){try{const saved=JSON.parse(sessionStorage.getItem('primeira-faisca-v7')||'null');if(saved?.version===7)state={...emptyState(),...saved};}catch{}}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600);}
function host(role,message,mode){text('hostRole',role);text('hostMessage',message);text('hostMode',mode||(geminiKey?'Gemini conectado':'modo local'));state.hostHistory.push({role,message,time:Date.now()});state.hostHistory=state.hostHistory.slice(-12);saveState();}
function hostThinking(on){$('hostBar').classList.toggle('thinking',on);}
function setAIStatus(message,connected=false){text('aiState',message);$('aiState').classList.toggle('connected',connected);text('aiTopStatus',connected?'Gemini ativo':'IA local');$('aiDot').classList.toggle('on',connected);}
function updateGlobal(view){const step=VIEW_STEP[view]??0;text('globalStep',STEP_LABEL[step]);$('globalProgress').style.width=`${step/6*100}%`;document.querySelectorAll('.bottomNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));}
function show(view,{force=false}={}){if(!VIEWS.includes(view))view='home';if(!force){if(view==='map'&&!state.deck.length)view='setup';if(view==='ritual'&&!state.deck.length)view='setup';if(view==='tarot'){if(!state.deck.length)view='setup';else if(state.index<state.deck.length)view='session';else if(!state.lastDice)view='ritual';}if(view==='closing'&&!state.tarotData)view='tarot';}VIEWS.forEach(v=>$(v)?.classList.toggle('hidden',v!==view));state.currentView=view;updateGlobal(view);window.scrollTo({top:0,behavior:'smooth'});if(view==='tarot')renderAutoContext();viewHost(view);saveState();}
function viewHost(view){const messages={home:['Dealer da experiência','Veja a sequência completa antes de começar; cada etapa prepara a próxima.'],setup:['Dealer da experiência','Definam o ritmo, a profundidade e quanto a anfitriã deve agir de forma proativa.'],session:['Dealer da jornada',currentPhase().description],map:['Diretora da experiência','Agora organizamos o percurso antes de criar o símbolo final.'],ritual:['Dealer do ritual','Os dados produzem um símbolo compartilhado que só entra no Tarô quando for guardado.'],tarot:['Cigana simbólica','A leitura reúne a pergunta, as cartas e o percurso inteiro.'],closing:['Editora final','O encerramento transforma a experiência em clareza e continuidade.'],kit:['Guia do kit','Cada peça física corresponde a um mecanismo do fluxo digital.'],credits:['Guia da experiência','Primeira Faísca foi concebido e dirigido por Esdra Felipe.']};const [r,m]=messages[view]||messages.home;host(r,m);}
function currentCard(){return state.deck[state.index]||null;}
function currentPhase(){const card=currentCard();return PHASES.find(p=>p.id===card?.phaseId)||PHASES[0];}
function topCategory(){return Object.entries(state.categories).sort((a,b)=>b[1]-a[1])[0]?.[0]||'';}

function audit(){const ids={};document.querySelectorAll('[id]').forEach(el=>ids[el.id]=(ids[el.id]||0)+1);const duplicates=Object.entries(ids).filter(([,n])=>n>1).map(([id])=>id);const required=['questionText','cardReason','answerGuide','startJourney','drawTarot','closingGrid'];const missing=required.filter(id=>!$(id));const badCards=CARD_BANK.filter(c=>!c.q.trim()||!c.w.trim()||!c.h.trim());const report={duplicates,missing,badCards:badCards.length,cards:CARD_BANK.length,lenormand:LENORMAND.length};if(duplicates.length||missing.length||badCards.length)console.warn('Auditoria v7',report);else console.info('Auditoria v7 aprovada',report);return report;}
function allocate(total){if(total===12)return[3,2,3,2,2];if(total===24)return[5,5,5,5,4];return[4,4,4,4,2];}
function phasePool(phase){let pool=CARD_BANK.filter(c=>phase.cats.includes(c.c)&&c.l<=state.level);if(!pool.length)pool=CARD_BANK.filter(c=>phase.cats.includes(c.c)&&c.l<=Math.min(3,state.level+1));return pool;}
function buildDeck(){const counts=allocate(state.duration),used=new Set(),deck=[];PHASES.forEach((phase,i)=>{const picked=[];for(const c of shuffle(phasePool(phase))){if(!used.has(c.id)){picked.push({...c,phaseId:phase.id});used.add(c.id);}if(picked.length===counts[i])break;}if(picked.length<counts[i])for(const c of shuffle(CARD_BANK.filter(c=>c.l<=Math.min(3,state.level+1)))){if(!used.has(c.id)){picked.push({...c,phaseId:phase.id});used.add(c.id);}if(picked.length===counts[i])break;}deck.push(...picked);});return deck.slice(0,state.duration);}
function startJourney(){const p1=$('p1').value.trim(),p2=$('p2').value.trim();if(!p1||!p2){text('setupError','Preencha os dois nomes.');return;}state={...emptyState(),p1,p2,duration:Number($('duration').value),level:Number(document.querySelector('#levels button.active')?.dataset.value||2),hostStyle:$('hostStyle').value,autonomy:$('autonomy').value,startedAt:Date.now(),currentView:'session'};state.deck=buildDeck();PHASES.forEach(p=>state.phaseStats[p.id]={seen:0,answered:0,skipped:0});if(!state.deck.length){text('setupError','O banco de cartas não carregou. Atualize a página.');return;}text('setupError','');show('session',{force:true});renderCard();announcePhase(currentPhase(),true);}
function renderTimeline(){const current=currentPhase(),idx=PHASES.findIndex(p=>p.id===current.id);$('phaseTimeline').innerHTML=PHASES.map((p,i)=>`<div class="${i<idx?'done':i===idx?'active':''}">${p.symbol} ${p.name}</div>`).join('');}
function renderCard(){if(state.index>=state.deck.length){finishJourney();return;}const card=currentCard(),phase=currentPhase();state.fav=false;$('favorite').textContent='♡';$('favorite').classList.remove('on');text('cardCounter',`${state.index+1} de ${state.deck.length}`);$('sessionProgress').style.width=`${state.index/state.deck.length*100}%`;text('phaseSymbol',phase.symbol);text('phaseName',phase.name);text('phaseDescription',phase.description);text('categoryBadge',`${ICONS[card.c]||'◌'} ${title(card.c)}`);text('levelBadge',`Nível ${card.l}`);text('turnLabel',`Vez de ${state.index%2===0?state.p1:state.p2}`);text('questionText',card.q,'Compartilhem algo importante sobre o tema.');text('cardReason',card.w,DEFAULT_REASON[card.c]||DEFAULT_REASON.conversa);text('answerGuide',card.h,DEFAULT_GUIDE[card.c]||DEFAULT_GUIDE.conversa);text('cardGuidance',card.d?'Atividade compartilhada: conversem antes, adaptem livremente e só realizem com concordância clara.':'Respondam apenas no nível de detalhe confortável para os dois.');$('insightInput').value='';renderTimeline();saveState();}
